services:
  modulartemplate.database:
    image: postgres:latest
    container_name: ModularTemplate.Database
    environment:
      - POSTGRES_DB=modulartemplate_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql
    ports:
      - 5432:5432

  modulartemplate.redis:
    image: redis:latest
    container_name: ModularTemplate.Redis
    restart: always
    ports:
      - 6379:6379
